export const GLOSSARY_TERM_MATCHERS = [
  { id: 'acid', match: { ru: ['ACID'], en: ['ACID'] } },
  {
    id: 'transaction',
    match: { ru: ['транзакция', 'транзакции'], en: ['transaction', 'transactions'] },
  },
  { id: 'index', match: { ru: ['индекс'], en: ['database index'] } },
  { id: 'primary-key', match: { ru: ['первичный ключ'], en: ['primary key'] } },
  { id: 'foreign-key', match: { ru: ['внешний ключ'], en: ['foreign key'] } },
  { id: 'join', match: { ru: [], en: [] } },
  { id: 'normalization', match: { ru: ['нормализация'], en: ['normalization'] } },
  { id: 'b-tree', match: { ru: ['B-дерево', 'B-дерева'], en: ['B-tree'] } },
  { id: 'mutability', match: { ru: ['изменяемость'], en: ['mutability'] } },
  { id: 'gil', match: { ru: ['GIL'], en: ['GIL'] } },
  { id: 'list-comprehension', match: { ru: ['list comprehension'], en: ['list comprehension'] } },
  { id: 'decorator', match: { ru: ['декоратор'], en: [] } },
  { id: 'generator', match: { ru: ['генератор'], en: [] } },
  { id: 'mro', match: { ru: ['MRO'], en: ['MRO'] } },
  { id: 'hash-table', match: { ru: ['хеш-таблица', 'хеш-таблицы'], en: ['hash table'] } },
  { id: 'big-o', match: { ru: ['O-большое'], en: ['Big-O'] } },
  {
    id: 'idempotency',
    match: { ru: ['идемпотентность', 'идемпотентный'], en: ['idempotency', 'idempotent'] },
  },
  { id: 'latency', match: { ru: ['латентность'], en: ['latency'] } },
  { id: 'throughput', match: { ru: ['пропускная способность'], en: ['throughput'] } },
  { id: 'embedding', match: { ru: ['эмбеддинг', 'эмбеддинги'], en: ['embedding', 'embeddings'] } },
  { id: 'token', match: { ru: ['токенизация'], en: ['tokenization'] } },
  { id: 'gradient-descent', match: { ru: ['градиентный спуск'], en: ['gradient descent'] } },
  { id: 'overfitting', match: { ru: ['переобучение'], en: ['overfitting'] } },
  { id: 'attention', match: { ru: ['механизм внимания'], en: ['attention mechanism'] } },
  {
    id: 'hallucination',
    match: { ru: ['галлюцинация', 'галлюцинации'], en: ['hallucination', 'hallucinations'] },
  },
  {
    id: 'namespace',
    match: { ru: ['пространство имён', 'пространства имён'], en: ['namespace'] },
  },
  { id: 'side-effect', match: { ru: ['сайд-эффект', 'сайд-эффекты'], en: ['side effect'] } },
  {
    id: 'file-descriptor',
    match: { ru: ['файловый дескриптор', 'файловых дескрипторов'], en: ['file descriptor'] },
  },
  {
    id: 'instantiation',
    match: {
      ru: ['инстанцирование', 'инстанцировании', 'инстанцируется'],
      en: ['instantiation'],
    },
  },
  { id: 'metaclass', match: { ru: ['метакласс', 'метаклассы'], en: ['metaclass'] } },
  {
    id: 'nominal-typing',
    match: { ru: ['номинальная типизация', 'номинальной типизации'], en: ['nominal typing'] },
  },
  {
    id: 'structural-typing',
    match: { ru: ['структурная типизация', 'структурной типизации'], en: ['structural typing'] },
  },
  {
    id: 'name-mangling',
    match: { ru: ['искажение имён', 'искажения имён'], en: ['name mangling'] },
  },
  { id: 'invariant', match: { ru: ['инвариант', 'инварианты', 'инвариантов'], en: ['invariant'] } },
  { id: 'descriptor', match: { ru: ['дескриптор', 'дескрипторы', 'дескрипторах'], en: ['descriptor'] } },
  {
    id: 'hashable',
    match: {
      ru: ['хэшируемость', 'хэшируемый', 'нехэшируемым', 'нехэшируемый'],
      en: ['hashable'],
    },
  },
  {
    id: 'dependency-injection',
    match: {
      ru: ['внедрение зависимости', 'внедрение зависимостей'],
      en: ['dependency injection'],
    },
  },
  { id: 'duck-typing', match: { ru: ['утиная типизация', 'утиной типизации'], en: ['duck typing'] } },
  {
    id: 'liskov-substitution-principle',
    match: { ru: ['принцип подстановки'], en: ['substitution principle'] },
  },
  { id: 'closure', match: { ru: ['замыкание', 'замыкания', 'замыкании'], en: ['closure'] } },
  { id: 'late-binding', match: { ru: ['позднее связывание'], en: ['late binding'] } },
  {
    id: 'first-class-functions',
    match: { ru: ['функции первого класса'], en: ['first-class functions'] },
  },
  {
    id: 'c3-linearization',
    match: { ru: ['C3-линеаризация', 'C3-линеаризации'], en: ['C3 linearization'] },
  },
  {
    id: 'diamond-inheritance',
    match: { ru: ['ромбовидное наследование', 'ромбовидного наследования'], en: ['diamond inheritance'] },
  },
  {
    id: 'cooperative-inheritance',
    match: {
      ru: ['кооперативное наследование', 'кооперативного наследования'],
      en: ['cooperative inheritance'],
    },
  },
  { id: 'mixin', match: { ru: ['миксин', 'миксины', 'миксина'], en: ['mixin'] } },
  { id: 'introspection', match: { ru: ['интроспекция', 'интроспекции'], en: ['introspection'] } },
  { id: 'coercion', match: { ru: ['коэрция', 'коэрции'], en: ['coercion'] } },
  {
    id: 'lexicographic-order',
    match: { ru: ['лексикографический порядок', 'лексикографически'], en: ['lexicographic order'] },
  },
  { id: 'variance-types', match: { ru: ['вариантность'], en: ['type variance'] } },
  { id: 'type-erasure', match: { ru: ['стирание типов', 'стёрт'], en: ['type erasure'] } },
  {
    id: 'gradual-typing',
    match: { ru: ['постепенная типизация', 'постепенной типизации'], en: ['gradual typing'] },
  },
  {
    id: 'iterator-protocol',
    match: { ru: ['протокол итерации', 'протокола итерации'], en: ['iterator protocol'] },
  },
  { id: 'dunder-methods', match: { ru: ['дандер-методы', 'дандер-метод'], en: ['dunder methods'] } },
  { id: 'bytecode', match: { ru: ['байткод', 'байткода'], en: ['bytecode'] } },
  {
    id: 'stack-frame',
    match: { ru: ['кадр выполнения', 'стек-фрейм'], en: ['stack frame'] },
  },
  {
    id: 'coroutine',
    match: {
      ru: ['корутина', 'корутины', 'корутину', 'сопрограмма', 'сопрограмму'],
      en: ['coroutine'],
    },
  },
  { id: 'logger-propagation', match: { ru: ['propagation'], en: ['logger propagation'] } },
  { id: 'contextvars', match: { ru: ['ContextVar', 'contextvars'], en: ['ContextVar', 'contextvars'] } },
  {
    id: 'loop-invariant',
    match: { ru: ['инвариант цикла', 'инварианты цикла'], en: ['loop invariant'] },
  },
  { id: 'stable-sort', match: { ru: ['устойчивая сортировка', 'устойчива'], en: ['stable sort'] } },
  { id: 'divide-and-conquer', match: { ru: ['разделяй и властвуй'], en: ['divide and conquer'] } },
  {
    id: 'reference-counting',
    match: { ru: ['подсчёт ссылок', 'счётчик ссылок'], en: ['reference counting'] },
  },
  { id: 'weak-reference', match: { ru: ['слабая ссылка', 'слабых ссылок'], en: ['weak reference'] } },
  {
    id: 'amortized-complexity',
    match: { ru: ['амортизированная сложность', 'амортизированно'], en: ['amortized complexity'] },
  },
  { id: 'load-factor', match: { ru: ['нагрузочный фактор'], en: ['load factor'] } },
  {
    id: 'open-addressing',
    match: { ru: ['открытая адресация', 'открытой адресации'], en: ['open addressing'] },
  },
  { id: 'identity-map', match: { ru: ['identity map'], en: ['identity map'] } },
  { id: 'unit-of-work', match: { ru: ['unit of work'], en: ['unit of work'] } },
  {
    id: 'n-plus-one',
    match: { ru: ['проблема N+1', 'N+1 запросов'], en: ['N+1 problem'] },
  },
  { id: 'lazy-loading', match: { ru: ['ленивая загрузка', 'ленивой загрузки'], en: ['lazy loading'] } },
  { id: 'eager-loading', match: { ru: ['жадная загрузка', 'жадной загрузки'], en: ['eager loading'] } },
  { id: 'sql-injection', match: { ru: ['SQL-инъекция', 'SQL-инъекции'], en: ['SQL injection'] } },
  {
    id: 'flaky-test',
    match: { ru: ['мигающий тест', 'мигающего теста', 'flaky'], en: ['flaky test'] },
  },
  { id: 'pytest-fixture', match: { ru: ['фикстура', 'фикстуры', 'фикстур'], en: ['fixture'] } },
  { id: 'mock-object', match: { ru: ['мок-объект', 'мок-объекты'], en: ['mock object'] } },
  { id: 'arrange-act-assert', match: { ru: ['Arrange-Act-Assert'], en: ['Arrange-Act-Assert'] } },
  { id: 'software-regression', match: { ru: [], en: [] } },
  { id: 'data-race', match: { ru: ['гонка данных', 'гонку данных'], en: ['data race'] } },
  { id: 'deadlock', match: { ru: ['взаимная блокировка', 'deadlock'], en: ['deadlock'] } },
  {
    id: 'critical-section',
    match: { ru: ['критическая секция', 'критической секции'], en: ['critical section'] },
  },
  { id: 'mutex-lock', match: { ru: ['мьютекс', 'мьютекса'], en: ['mutex'] } },
  { id: 'semaphore', match: { ru: ['семафор', 'семафора'], en: ['semaphore'] } },
  { id: 'event-loop', match: { ru: ['event loop'], en: ['event loop'] } },
  { id: 'heisenbug', match: { ru: ['гейзенбаг', 'гейзенбаги'], en: ['heisenbug'] } },
  {
    id: 'context-switch',
    match: { ru: ['переключение контекста', 'переключения контекста'], en: ['context switch'] },
  },
  { id: 'producer-consumer', match: { ru: ['производитель-потребитель'], en: ['producer-consumer'] } },
  { id: 'io-bound-cpu-bound', match: { ru: ['IO-bound', 'CPU-bound'], en: ['IO-bound', 'CPU-bound'] } },
  { id: 'bias', match: { ru: ['bias (смещение)'], en: ['bias'] } },
  { id: 'sigmoid', match: { ru: ['сигмоида', 'сигмоиды'], en: ['sigmoid'] } },
  {
    id: 'activation-function',
    match: { ru: ['функция активации', 'функции активации'], en: ['activation function'] },
  },
  { id: 'relu', match: { ru: ['ReLU'], en: ['ReLU'] } },
  { id: 'softmax', match: { ru: ['softmax', 'Softmax'], en: ['softmax'] } },
  {
    id: 'backpropagation',
    match: { ru: ['обратное распространение', 'обратного распространения'], en: ['backpropagation'] },
  },
  { id: 'learning-rate', match: { ru: ['learning rate'], en: ['learning rate'] } },
  { id: 'dropout', match: { ru: ['dropout', 'Dropout'], en: ['dropout'] } },
  { id: 'underfitting', match: { ru: ['недообучение', 'недообучения'], en: ['underfitting'] } },
  { id: 'epoch', match: { ru: ['эпоха', 'эпохах', 'эпох'], en: ['epoch'] } },
  { id: 'mlp', match: { ru: ['MLP'], en: ['MLP'] } },
  { id: 'cnn', match: { ru: ['свёрточная сеть', 'CNN'], en: ['CNN'] } },
  { id: 'inference', match: { ru: ['инференс', 'инференсе'], en: ['inference'] } },
  {
    id: 'transformer',
    match: { ru: ['трансформер', 'трансформеры', 'трансформере'], en: ['transformer'] },
  },
  {
    id: 'fine-tuning',
    match: { ru: ['дообучение', 'дообучения', 'fine-tuning'], en: ['fine-tuning'] },
  },
  { id: 'iou', match: { ru: ['IoU'], en: ['IoU'] } },
  {
    id: 'anchor-box',
    match: { ru: ['якорная рамка', 'якорной рамке', 'якорь'], en: ['anchor box'] },
  },
  { id: 'nms', match: { ru: ['Non-Maximum Suppression', 'NMS'], en: ['Non-Maximum Suppression'] } },
  {
    id: 'bounding-box',
    match: { ru: ['ограничивающая рамка', 'ограничивающей рамки', 'bounding box'], en: ['bounding box'] },
  },
  { id: 'objectness', match: { ru: ['objectness'], en: ['objectness'] } },
  { id: 'map-metric', match: { ru: ['mAP'], en: ['mAP'] } },
  { id: 'precision', match: { ru: ['precision'], en: ['precision'] } },
  { id: 'recall', match: { ru: ['recall'], en: ['recall'] } },
  { id: 'focal-loss', match: { ru: ['focal loss'], en: ['focal loss'] } },
  { id: 'autoregression', match: { ru: ['авторегрессия', 'авторегрессии'], en: ['autoregression'] } },
  { id: 'logits', match: { ru: ['логиты', 'логитов'], en: ['logits'] } },
  { id: 'temperature', match: { ru: ['температура генерации', 'температуре'], en: ['temperature'] } },
  {
    id: 'greedy-decoding',
    match: { ru: ['жадный выбор', 'жадного выбора'], en: ['greedy decoding'] },
  },
  { id: 'top-k', match: { ru: ['top-k'], en: ['top-k'] } },
  { id: 'top-p', match: { ru: ['top-p'], en: ['top-p'] } },
  { id: 'bpe', match: { ru: ['BPE'], en: ['BPE'] } },
  {
    id: 'context-window',
    match: { ru: ['контекстное окно', 'контекстного окна'], en: ['context window'] },
  },
  {
    id: 'cosine-similarity',
    match: { ru: ['косинусная близость', 'косинусной близости'], en: ['cosine similarity'] },
  },
  {
    id: 'positional-encoding',
    match: { ru: ['позиционное кодирование', 'позиционного кодирования', 'RoPE'], en: ['positional encoding'] },
  },
  {
    id: 'query-key-value',
    match: { ru: ['query, key, value', 'query/key/value'], en: ['query, key, value'] },
  },
  {
    id: 'multi-head-attention',
    match: { ru: ['многоголовое внимание', 'многоголового внимания'], en: ['multi-head attention'] },
  },
  { id: 'pretraining', match: { ru: ['предобучение', 'предобучения'], en: ['pretraining'] } },
  { id: 'alignment', match: { ru: ['выравнивание модели'], en: ['alignment'] } },
  { id: 'sft', match: { ru: ['SFT'], en: ['SFT'] } },
  { id: 'rlhf', match: { ru: ['RLHF'], en: ['RLHF'] } },
  { id: 'dpo', match: { ru: ['DPO'], en: ['DPO'] } },
  { id: 'lora', match: { ru: ['LoRA'], en: ['LoRA'] } },
  { id: 'scaling-laws', match: { ru: ['законы масштабирования'], en: ['scaling laws'] } },
  {
    id: 'knowledge-cutoff',
    match: { ru: ['дата отсечки данных', 'дату отсечки'], en: ['knowledge cutoff'] },
  },
  { id: 'model-weights', match: { ru: ['веса модели', 'весах модели'], en: ['model weights'] } },
  {
    id: 'function-calling',
    match: { ru: ['вызов инструментов'], en: ['function calling'] },
  },
  { id: 'llm-agent', match: { ru: [], en: [] } },
  { id: 'agent-skills', match: { ru: ['навыки (skills)'], en: ['agent skills'] } },
  {
    id: 'system-prompt',
    match: { ru: ['системный промпт', 'системного промпта'], en: ['system prompt'] },
  },
  { id: 'zero-shot', match: { ru: ['zero-shot'], en: ['zero-shot'] } },
  { id: 'few-shot', match: { ru: ['few-shot'], en: ['few-shot'] } },
  { id: 'in-context-learning', match: { ru: ['обучение в контексте'], en: ['in-context learning'] } },
  {
    id: 'chain-of-thought',
    match: {
      ru: ['цепочка рассуждений', 'цепочки рассуждений', 'chain of thought'],
      en: ['chain of thought'],
    },
  },
  {
    id: 'structured-output',
    match: { ru: ['структурный вывод', 'структурного вывода'], en: ['structured output'] },
  },
  { id: 'grounding', match: { ru: ['заземление'], en: ['grounding'] } },
  { id: 'rag', match: { ru: ['RAG'], en: ['RAG'] } },
  { id: 'prompt-injection', match: { ru: ['prompt injection'], en: ['prompt injection'] } },
  { id: 'react-pattern', match: { ru: ['ReAct'], en: ['ReAct'] } },
  { id: 'self-consistency', match: { ru: ['self-consistency'], en: ['self-consistency'] } },
  { id: 'llm-as-judge', match: { ru: ['LLM-as-judge'], en: ['LLM-as-judge'] } },
];
